/* Generated By:JJTree&JavaCC: Do not edit this line. FCONSTRAINTConstants.java */
package br.usp.icmc.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FCONSTRAINTConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEG = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int LETTER = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"!\"",
    "\"&\"",
    "\"||\"",
    "<ID>",
    "<LETTER>",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
