(define-sort Feature () Bool)
(declare-const G Feature)
(declare-const A Feature)
(declare-const M Feature)
(declare-const L Feature)
(declare-const C Feature)
(declare-const R Feature)
(declare-const B Feature)
(declare-const N Feature)
(declare-const W Feature)
(declare-const V Feature)
(declare-const Y Feature)
(declare-const P Feature)
(declare-const S Feature)

(assert G)
(assert (and
   (= A G)
   (= M A)
   (= L A)
   (= C G)
   (= R G)
   (= (or B  N  W ) R)
   (not (and B N))
   (not (and B W))
   (not (and N W))
   (= V G)
   (= Y V)
   (= P V)
   (=> S V)
))

(push)
(assert (and true S))
(assert (and S true N S true N true N))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S true N true W))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S true N true B))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S true W true N))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S true W true W))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S true W true B))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S true B true N))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S true B true W))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S true B true B))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S (not W) true (not W) S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S (not W) true W S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S W true (not W) S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S W true W S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S (or (not W) S) true true S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S (and W (not S)) true true S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and S true N S S true true S))
(check-sat)
(pop)
