(define-sort Feature () Bool)
(declare-const G Feature)
(declare-const A Feature)
(declare-const M Feature)
(declare-const L Feature)
(declare-const C Feature)
(declare-const R Feature)
(declare-const B Feature)
(declare-const N Feature)
(declare-const W Feature)
(declare-const V Feature)
(declare-const Y Feature)
(declare-const P Feature)
(declare-const S Feature)

(assert G)
(assert (and
   (= A G)
   (= M A)
   (= L A)
   (= C G)
   (= R G)
   (= (or B  N  W ) R)
   (not (and B N))
   (not (and B W))
   (not (and N W))
   (= V G)
   (= Y V)
   (= P V)
   (=> S V)
))

(push)
(assert (and true S))
(assert (and true N true N))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true N true W))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true N true B))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true W true N))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true W true W))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true W true B))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true B true N))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true B true W))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true B true B))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true true (not W) S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true true W S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and true true true S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and B S true S))
(check-sat)
(pop)
(push)
(assert (and true S))
(assert (and N S true S))
(check-sat)
(pop)
