/* Generated By:JavaCC: Do not edit this line. FCONSTRAINTTreeConstants.java Version 5.0 */
package parser.yakindu;

public interface FCONSTRAINTTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTTERM = 1;
  public int JJTUNARY = 2;
  public int JJTELEMENT = 3;
  public int JJTNEG = 4;
  public int JJTAND = 5;
  public int JJTOR = 6;
  public int JJTID = 7;


  public String[] jjtNodeName = {
    "Parse",
    "term",
    "unary",
    "element",
    "neg",
    "and",
    "or",
    "id",
  };
}
/* JavaCC - OriginalChecksum=1a5a60368993551abc4edacf928e77f0 (do not edit this line) */
